services:
  - type: web
    name: django-backend
    plan: free
    env: python
    region: singapore  # You can change it. Options are [Oregon, Frankfurt, Ohio, Singapore] but remember, it should same in everywhere.
    buildCommand: "./api-server-django/build.sh"
    startCommand: |
      cd api-server-django
      gunicorn core.wsgi --bind 0.0.0.0:$PORT
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: soft_ui_db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4

  - type: web
    name: react-frontend
    plan: free
    env: node
    region: singapore   # You can change it. Options are [Oregon, Frankfurt, Ohio, Singapore] but remember, it should same in everywhere.
    buildCommand: "./react-ui/build.sh"
    startCommand: |
      cd react-ui
      serve -s build
    envVars:
      - key: NODE_ENV
        value: "production"
      - key: REACT_APP_BACKEND_SERVER
        value: "https://django-backend-g3hd.onrender.com/api/"  # Change it with your backend server

databases:
  - name: soft_ui_db
    databaseName: soft_ui_db
    user: soft_ui_db
    plan: free
    region: singapore  # You can change it. Options are [Oregon, Frankfurt, Ohio, Singapore] but remember, it should same in everywhere.
